name: online_food_order_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  loading_animation_widget: ^1.2.0+4
  flutter_slider_drawer: ^2.1.3
  dio: ^5.3.4
  curved_navigation_bar: ^1.0.3
  badges: ^3.1.2
  intl: ^0.17.0
  alert_dialog: ^1.0.2
  font_awesome_flutter: ^10.6.0
  snackbar: ^1.0.2
  cool_alert: ^2.0.1
  flutter_slidable: ^3.0.1
  cupertino_modal_sheet: ^1.1.0
  bottom_sheet: ^4.0.0
  easy_loading_button: ^0.3.2
  modal_progress_hud_nsn: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - asset/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware


  fonts:
     - family: Poppins Bold
       fonts:
         - asset: fonts/Poppins-Bold.ttf
     - family: Poppins Light
       fonts:
         - asset: fonts/Poppins-Light.ttf

     - family: Poppins Regular
       fonts:
         - asset: fonts/Poppins-Regular.ttf

     - family: Poppins Medium
       fonts:
         - asset: fonts/Poppins-Medium.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
